[default]
features = "default"
engine = "Llvm"

[json]
features = "json"
engine = "Llvm"

[parallel]
features = "parallel"
engine = "Llvm"

[json_parallel]
features = "json,parallel"
engine = "Llvm"

[report]
output-dir = "website"
out = [ "Html" ]